import {
  Globe,
  Palette,
  ShieldAlert,
  Users,
  Key,
  Compass,
  Calendar,
  CheckSquare,
  MessageSquare,
  Radio,
  Bell,
  Sparkles,
  HardDrive,
  BarChart3,
  Zap,
  Webhook,
  Moon,
  Lock,
  FileText,
  RotateCcw,
  Code,
  Building2,
  Database,
  Cpu,
  Server,
  DollarSign,
  AlertTriangle,
} from "lucide-react";

export const SETTINGS_DOMAINS = [
  {
    title: "Core Workspace & Branding",
    categories: [
      {
        id: "general",
        name: "General Workspace Settings",
        icon: Globe,
        badge: "CORE",
        badgeColor: "bg-cyan-500/20 text-cyan-300 border-cyan-500/40",
        description: "Configure overall workspace identity, university charter, timezone, locale, and semester working calendars.",
        compliance: "ISO-27001 COMPLIANT",
        related: ["branding", "appearance", "multiTenancy"],
        fields: [
          { key: "orgName", label: "Organization Name", type: "text", default: "ClubPlanet OrgOS Enterprise" },
          { key: "universityName", label: "Charter University", type: "text", default: "Indian Institute of Technology / Campus HQ" },
          { key: "academicYear", label: "Active Academic Year", type: "select", default: "2026-2027", options: ["2025-2026", "2026-2027", "2027-2028"] },
          { key: "timezone", label: "Primary Timezone", type: "select", default: "Asia/Kolkata (UTC+5:30)", options: ["Asia/Kolkata (UTC+5:30)", "America/New_York (UTC-5)", "Europe/London (UTC+0)"] },
          { key: "workingDays", label: "Semester Working Days", type: "multi", default: "Monday — Saturday" },
          { key: "supportEmail", label: "Official Governance Email", type: "text", default: "governance@clubplanet.edu" },
        ],
      },
      {
        id: "branding",
        name: "Organization Branding",
        icon: Palette,
        description: "Complete white-label customization of logos, favicons, splash screens, certificate watermarks, and login aesthetics.",
        compliance: "WHITE-LABEL ACTIVE",
        related: ["general", "appearance"],
        fields: [
          { key: "accentPalette", label: "Primary Neon Accent Palette", type: "select", default: "Electric Violet (#7C3AED) + Neon Cyan (#06B6D4)", options: ["Electric Violet (#7C3AED) + Neon Cyan (#06B6D4)", "Obsidian Emerald (#10B981) + Cyan", "Cyber Gold (#F59E0B) + Violet"] },
          { key: "certificateWatermark", label: "Event Certificate Watermark", type: "toggle", default: true, help: "Embed university seal watermark on generated PDF certificates." },
          { key: "loginSplash", label: "Custom Login Background Shader", type: "toggle", default: true },
          { key: "customCss", label: "Custom CSS / Override Engine", type: "toggle", default: false },
        ],
      },
      {
        id: "appearance",
        name: "Appearance & Display Engine",
        icon: Moon,
        description: "Configure hardware-accelerated 60 FPS Framer Motion animations, dark glassmorphism blur intensity, and layout density.",
        compliance: "60 FPS RENDER SLA",
        related: ["general", "branding"],
        fields: [
          { key: "fps60Mode", label: "60 FPS Hardware Acceleration", type: "toggle", default: true, help: "Enables GPU-accelerated Framer Motion transforms and smooth particle lighting." },
          { key: "glassBlurQuality", label: "Glassmorphic Backdrop Blur", type: "select", default: "High (24px Frosted Glass)", options: ["High (24px Frosted Glass)", "Medium (12px Blur)", "Low (Performance Mode)"] },
          { key: "compactSidebar", label: "Compact Sidebar Layout", type: "toggle", default: false },
        ],
      },
    ],
  },
  {
    title: "Security, RBAC & Governance",
    categories: [
      {
        id: "security",
        name: "Authentication & Security",
        icon: ShieldAlert,
        badge: "CRITICAL",
        badgeColor: "bg-red-500/20 text-red-300 border-red-500/40",
        description: "Enterprise authentication controls, hardware TOTP 2FA, session timeout, active devices, login history, and IP restrictions.",
        compliance: "SOC2 TYPE II / MFA REQUIRED",
        related: ["rbac", "userMgmt", "compliance"],
        fields: [
          { key: "requireMfa", label: "Enforce Hardware TOTP 2FA for Presidents", type: "toggle", default: true, warning: "Disabling MFA will downgrade SOC2 security rating for budget approvers." },
          { key: "sessionTimeoutMin", label: "Idle Session Timeout (Minutes)", type: "number", default: "30" },
          { key: "ipWhitelist", label: "University Campus IP Range Whitelist", type: "text", default: "192.168.1.0/24; 10.240.0.0/16" },
          { key: "failedLoginLockout", label: "Account Lockout After Failed Logins", type: "select", default: "5 Failed Attempts (30 Min Lockout)", options: ["3 Failed Attempts", "5 Failed Attempts (30 Min Lockout)", "10 Failed Attempts"] },
        ],
      },
      {
        id: "userMgmt",
        name: "User & Directory Management",
        icon: Users,
        description: "Manage platform user directory, bulk CSV import/export, student coordinators, alumni, faculty advisors, and guests.",
        compliance: "DIRECTORY SYNC",
        related: ["security", "rbac"],
        fields: [
          { key: "allowGuestAccess", label: "Allow Inter-University Guest Accounts", type: "toggle", default: true },
          { key: "autoAlumniConversion", label: "Auto-Convert Graduating Seniors to Alumni", type: "toggle", default: true },
          { key: "maxUsersPerClub", label: "Max Chartered Members per Club", type: "number", default: "500" },
        ],
      },
      {
        id: "rbac",
        name: "RBAC Role & Permission Management",
        icon: Key,
        badge: "RBAC",
        badgeColor: "bg-violet-500/20 text-violet-300 border-violet-500/40",
        description: "Advanced Role-Based Access Control, permission inheritance, module overrides, approval workflows, and temporary delegations.",
        compliance: "HIERARCHY ENFORCED",
        related: ["security", "userMgmt"],
        fields: [
          { key: "budgetApprovalThreshold", label: "Presidential Budget Approval Limit (USD)", type: "number", default: "5000" },
          { key: "inheritFacultyPerms", label: "Faculty Advisors Inherit Super-Admin Read", type: "toggle", default: true },
          { key: "tempDelegationDays", label: "Max Temporary Role Delegation (Days)", type: "number", default: "14" },
        ],
      },
      {
        id: "compliance",
        name: "Compliance, FERPA & Privacy",
        icon: Lock,
        badge: "LEGAL",
        badgeColor: "bg-amber-500/20 text-amber-300 border-amber-500/40",
        description: "Enterprise FERPA educational privacy, GDPR readiness, consent settings, cookie management, and legal audit exports.",
        compliance: "FERPA + GDPR READINESS",
        related: ["security", "auditLogs"],
        fields: [
          { key: "ferpaStudentPrivacy", label: "Enforce FERPA Student Directory Privacy", type: "toggle", default: true, help: "Hides student phone numbers and academic GPA from standard members." },
          { key: "gdprConsentBanner", label: "Require GDPR Cookie & Telemetry Consent", type: "toggle", default: true },
          { key: "dataRetentionYears", label: "Graduated Student Data Retention (Years)", type: "select", default: "5 Years (Academic Archive)", options: ["1 Year", "5 Years (Academic Archive)", "Indefinite"] },
        ],
      },
      {
        id: "multiTenancy",
        name: "Multi-Tenancy & Org Isolation",
        icon: Building2,
        description: "Manage department/faculty hierarchical isolation, student graduation offboarding, and club dissolution workflows.",
        compliance: "TENANT ISOLATED",
        related: ["general", "compliance"],
        fields: [
          { key: "tenantIsolation", label: "Enforce Faculty/Department Tenant Boundaries", type: "toggle", default: true },
          { key: "clubDissolutionPolicy", label: "Club Dissolution Data Handling", type: "select", default: "Archive to Academic Vault (Read-Only)", options: ["Archive to Academic Vault (Read-Only)", "Transfer Ownership to Student Council", "Permanent Deletion after 90 Days"] },
        ],
      },
    ],
  },
  {
    title: "OrgOS Module Configuration",
    categories: [
      {
        id: "clubGov",
        name: "Club Management Settings",
        icon: Compass,
        description: "Configure campus recruitment windows, membership/committee limits, automatic joining rules, and archival lifecycles.",
        compliance: "CHARTER VERIFIED",
        related: ["rbac", "eventConfig"],
        fields: [
          { key: "openRecruitment", label: "Campus-Wide Open Recruitment Window", type: "toggle", default: true },
          { key: "maxCommitteesPerStudent", label: "Max Simultaneous Committees per Student", type: "number", default: "4" },
          { key: "autoApproveMembers", label: "Auto-Approve Open Orbit Joining Requests", type: "toggle", default: false },
        ],
      },
      {
        id: "eventConfig",
        name: "Event & RSVP Configuration",
        icon: Calendar,
        description: "Configure RSVP ticketing rules, registration capacity limits, holographic QR pass generation, and digital certificates.",
        compliance: "QR CRYPTO PASS",
        related: ["clubGov", "automation"],
        fields: [
          { key: "qrPassCrypto", label: "Encrypt Holographic QR Pass Tokens", type: "toggle", default: true },
          { key: "defaultCapacity", label: "Default Flagship Event Seat Capacity", type: "number", default: "1500" },
          { key: "autoWaitlist", label: "Auto-Promote Waitlisted Students on Cancellation", type: "toggle", default: true },
        ],
      },
      {
        id: "taskConfig",
        name: "Task Management Settings",
        icon: CheckSquare,
        description: "Configure Linear/ClickUp Kanban default columns, priority colored badges, due date automation, and recurrence.",
        compliance: "SPRINT VELOCITY",
        related: ["automation", "chatConfig"],
        fields: [
          { key: "defaultColumns", label: "Kanban Board Columns", type: "text", default: "TODO, IN PROGRESS, IN REVIEW, COMPLETED" },
          { key: "autoArchiveCompletedDays", label: "Auto-Archive Completed Sprint Tasks (Days)", type: "number", default: "14" },
        ],
      },
      {
        id: "chatConfig",
        name: "Chat & Communication",
        icon: MessageSquare,
        description: "Manage channel messaging permissions, AI typing indicators, message deletion policies, file upload size, and moderation.",
        compliance: "E2E SOCKET SYNC",
        related: ["taskConfig", "aiConfig"],
        fields: [
          { key: "maxUploadMb", label: "Standard Attachment Limit — Gmail/Outlook Email Compatible (MB)", type: "number", default: "25" },
          { key: "maxResumableUploadMb", label: "Tus Resumable Document Mode Limit — WhatsApp/Telegram Standard (MB)", type: "number", default: "2048" },
          { key: "enableClientImageCompression", label: "Auto-Compress Photos on Client Browser (10MB RAW Cap → <1MB WebP)", type: "toggle", default: true },
          { key: "enableAiModeration", label: "Real-Time AI Word Filter & Moderation", type: "toggle", default: true },
          { key: "readReceipts", label: "Show Online Read Receipts", type: "toggle", default: true },
        ],
      },
      {
        id: "meetingConfig",
        name: "Meeting Management",
        icon: Radio,
        description: "Configure audio recording rules, AI transcription retention, Neural Executive Summaries, and Action Item Kanban sync.",
        compliance: "AI TRANSCRIBER ONLINE",
        related: ["aiConfig", "taskConfig"],
        fields: [
          { key: "autoAiSummary", label: "Generate AI Summary on Recording End", type: "toggle", default: true },
          { key: "transcriptRetentionDays", label: "Meeting Transcript Retention (Days)", type: "number", default: "365" },
          { key: "autoSyncKanban", label: "Auto-Push Extracted Action Items to Kanban", type: "toggle", default: true },
        ],
      },
      {
        id: "notifConfig",
        name: "Notification Center",
        icon: Bell,
        description: "Configure real-time push alerts, daily morning email digests, silent hours, and priority budget approval alerts.",
        compliance: "REAL-TIME TELEMETRY",
        related: ["security", "automation"],
        fields: [
          { key: "dailyDigestTime", label: "Daily Email Digest Time", type: "select", default: "08:00 AM (Campus Time)", options: ["08:00 AM (Campus Time)", "06:00 PM (Campus Time)", "Disabled"] },
          { key: "silentHours", label: "Silent Hours (No Push Notifications)", type: "text", default: "11:00 PM — 07:00 AM" },
          { key: "urgentBudgetPush", label: "High-Priority Push for Requisitions >$1,000", type: "toggle", default: true },
        ],
      },
    ],
  },
  {
    title: "Intelligence, Automation & Integrations",
    categories: [
      {
        id: "aiConfig",
        name: "AI Configuration & Quotas",
        icon: Sparkles,
        badge: "AI",
        badgeColor: "bg-pink-500/20 text-pink-300 border-pink-500/40",
        description: "Configure OrgOS AI LLM provider, prompt templates, cost monitoring, token usage analytics, and meeting summarizers.",
        compliance: "GEMINI 2.5 PRO / FLASH",
        related: ["meetingConfig", "chatConfig"],
        fields: [
          { key: "aiProvider", label: "Primary Neural AI Engine", type: "select", default: "Google Gemini 2.5 Pro (Enterprise)", options: ["Google Gemini 2.5 Pro (Enterprise)", "Google Gemini 2.5 Flash (Low-Latency)", "Hybrid Multi-Model"] },
          { key: "monthlyTokenQuota", label: "Monthly Organization Token Quota (Millions)", type: "number", default: "100" },
          { key: "aiAnnouncementDrafting", label: "AI Announcement & Email Drafting Bot", type: "toggle", default: true },
        ],
      },
      {
        id: "automation",
        name: "Workflow Automation & Cron",
        icon: Zap,
        description: "Configure automated workflows, member onboarding sequences, event RSVP reminder cron jobs, and auto-archival.",
        compliance: "CRON WORKERS ACTIVE",
        related: ["eventConfig", "notifConfig"],
        fields: [
          { key: "onboardingWelcomeEmail", label: "Auto-Send Onboarding Kit to New Members", type: "toggle", default: true },
          { key: "rsvpReminderCron", label: "RSVP Reminder Notification Cron", type: "select", default: "24 Hours & 2 Hours Before Event", options: ["24 Hours & 2 Hours Before Event", "2 Hours Before Event", "Disabled"] },
        ],
      },
      {
        id: "integrations",
        name: "Webhooks & External Integrations",
        icon: Webhook,
        description: "Connect third-party developer webhooks, Google Workspace calendar sync, Discord #announcements mirror, and GitHub.",
        compliance: "REST API v2.4",
        related: ["developer", "general"],
        fields: [
          { key: "discordWebhookUrl", label: "Discord Mirror Webhook URL", type: "text", default: "https://discord.com/api/webhooks/12345/orgos-announcements" },
          { key: "googleCalendarSync", label: "Google Workspace Campus Calendar Sync", type: "toggle", default: true },
          { key: "githubRepoSync", label: "GitHub Enterprise Committee Repo Linking", type: "toggle", default: true },
        ],
      },
    ],
  },
  {
    title: "Infrastructure, Logs & Resilience",
    categories: [
      {
        id: "storage",
        name: "CDN & File Storage Configuration",
        icon: HardDrive,
        description: "Manage AWS S3 / Cloudflare CDN storage buckets, attachment quotas, allowed MIME types, and automated virus scanning.",
        compliance: "CLOUDFLARE R2 + SCAN",
        related: ["chatConfig", "backup"],
        fields: [
          { key: "storageProvider", label: "Primary Storage & CDN Engine", type: "select", default: "AWS S3 Multi-Region Enterprise + Cloudflare CDN", options: ["AWS S3 Multi-Region Enterprise + Cloudflare CDN", "Google Cloud Storage Bucket"] },
          { key: "virusScanning", label: "Real-Time ClamAV Attachment Scanning", type: "toggle", default: true },
          { key: "maxOrgStorageGb", label: "Total Organization Storage Quota (GB)", type: "number", default: "5000" },
        ],
      },
      {
        id: "analytics",
        name: "Analytics & KPI Reporting",
        icon: BarChart3,
        description: "Configure real-time dashboard KPI metrics, event attendance heatmaps, budget burn-down exports, and scheduled reports.",
        compliance: "60 FPS TELEMETRY",
        related: ["general", "resourceGov"],
        fields: [
          { key: "realtimeTelemetry", label: "Live WebSocket System Telemetry Stream", type: "toggle", default: true },
          { key: "scheduledReportDay", label: "Weekly Executive Digest Delivery Day", type: "select", default: "Monday Morning (08:00 AM)", options: ["Monday Morning (08:00 AM)", "Friday Evening (05:00 PM)"] },
        ],
      },
      {
        id: "auditLogs",
        name: "Tamper-Evident Audit Logs",
        icon: FileText,
        badge: "IMMUTABLE",
        badgeColor: "bg-emerald-500/20 text-emerald-300 border-emerald-500/40",
        description: "Enterprise write-once cryptographic hash-chaining audit logs tracking every approval, login, and configuration change.",
        compliance: "APPEND-ONLY HASH CHAIN",
        related: ["compliance", "security"],
        fields: [
          { key: "cryptographicHashChain", label: "Enforce Append-Only Cryptographic Hash Chaining", type: "toggle", default: true, help: "Ensures no administrator can alter or erase historical governance approval logs." },
          { key: "logRetentionDays", label: "Audit Log Archive Retention (Days)", type: "number", default: "2555" },
        ],
      },
      {
        id: "backup",
        name: "Backup, Rollback & Disaster Recovery",
        icon: RotateCcw,
        badge: "RECOVERY",
        badgeColor: "bg-cyan-500/20 text-cyan-300 border-cyan-500/40",
        description: "Configure automated database snapshots, 'Last Known Good Configuration' restore points, and break-glass recovery.",
        compliance: "HOURLY SNAPSHOT SLA",
        related: ["storage", "auditLogs"],
        fields: [
          { key: "autoSnapshotInterval", label: "Automated DB Snapshot Frequency", type: "select", default: "Hourly Incremental + Daily Full DB Snapshot", options: ["Hourly Incremental + Daily Full DB Snapshot", "Daily Snapshot Only"] },
          { key: "enableSafeMode", label: "Safe Mode Read-Only Toggle During Maintenance", type: "toggle", default: false, warning: "Enabling Safe Mode locks out all non-super-admin writes across OrgOS." },
        ],
      },
      {
        id: "developer",
        name: "Developer Settings & API Keys",
        icon: Code,
        description: "Manage OAuth 2.0 Clients, REST API Bearer tokens, rate limiting rules, beta feature flags, and debug telemetry.",
        compliance: "API GATEWAY 12.4ms",
        related: ["integrations", "security"],
        fields: [
          { key: "rateLimitRpm", label: "Max API Requests per Minute (per Token)", type: "number", default: "600" },
          { key: "enableBetaFeatures", label: "Enable Experimental OrgOS v2.5 Beta Flags", type: "toggle", default: true },
          { key: "debugTelemetry", label: "Verbose Console & WebSocket Telemetry", type: "toggle", default: false },
        ],
      },
    ],
  },
];
