// Metro Tunnel Line Definitions for ClubPlanet 3D Campus Universe
// Line A: Chartered Clubs & Societies
// Line B: Upcoming Flagship Events & Championships
// Line C: Executive Governance & 21-Module Enterprise Settings

export const METRO_LINES = {
  LINE_A: {
    id: "LINE_A",
    name: "LINE A // CLUBS & SOCIETIES",
    shortName: "CLUBS METRO",
    badge: "6 STATIONS",
    themeColor: "#06B6D4",
    secondaryColor: "#7C3AED",
    bgClass: "bg-cyan-500/15 text-cyan-300 border-cyan-400/50",
    stations: [
      {
        index: 1,
        id: "abacus",
        type: "CLUB",
        title: "01. ABACUS QUANT SOCIETY",
        subtitle: "Algorithmic Trading • 140 Members • $1,250 Budget",
        color: "#7C3AED",
        z: -12,
        details: "Chartered Quantitative Economics & Trading Collective. Active sprint: High-Frequency Options Model Review and Bloomberg Terminal API integration.",
        stats: [
          { label: "MEMBERSHIP", val: "140 / 150 MAX", color: "text-cyan-400" },
          { label: "ANNUAL BUDGET", val: "$1,250 USD", color: "text-emerald-400" },
          { label: "ACTIVE SPRINT", val: "V2 TRADING ALGO", color: "text-violet-400" },
        ],
        ctaLabel: "Open 2D Club Page",
        ctaUrl: "/clubs",
      },
      {
        index: 2,
        id: "robotics",
        type: "CLUB",
        title: "02. ROBOTICS CORE TECH",
        subtitle: "Autonomous ROS2 Lab • 210 Members • V2.4 Firmware",
        color: "#06B6D4",
        z: -28,
        details: "Official AI & Mechatronics Robotics Hub. Active sprint: 20 LiPo Battery ESC Controller Calibration and LiDAR Mapping Rover testing.",
        stats: [
          { label: "MEMBERSHIP", val: "210 ENG STUDENTS", color: "text-cyan-400" },
          { label: "HARDWARE LAB", val: "ROOM 402B OPEN", color: "text-emerald-400" },
          { label: "ROS2 FIRMWARE", val: "v2.4.1 STABLE", color: "text-violet-400" },
        ],
        ctaLabel: "Open 2D Club Page",
        ctaUrl: "/clubs",
      },
      {
        index: 3,
        id: "symphony",
        type: "CLUB",
        title: "03. SYMPHONY ACOUSTICS",
        subtitle: "Campus Orchestra • 95 Members • Dolby Surround Lab",
        color: "#EC4899",
        z: -44,
        details: "Premier university musical society and acoustics engineering group. Currently rehearsing for Annual Symphony Live Concert at Open Air Theatre.",
        stats: [
          { label: "MEMBERSHIP", val: "95 MUSICIANS", color: "text-pink-400" },
          { label: "INSTRUMENT POOL", val: "$3,400 ASSETS", color: "text-emerald-400" },
          { label: "REHEARSAL ROOM", val: "STUDIO A ACTIVE", color: "text-violet-400" },
        ],
        ctaLabel: "Open 2D Club Page",
        ctaUrl: "/clubs",
      },
      {
        index: 4,
        id: "ai_research",
        type: "CLUB",
        title: "04. AI & DEEP LEARNING CORE",
        subtitle: "LLM Research & Vision • 180 Members • H100 Cluster",
        color: "#3B82F6",
        z: -60,
        details: "Dedicated student research lab specializing in Generative AI, Multimodal Transformer architectures, and campus AI workflow automation.",
        stats: [
          { label: "MEMBERSHIP", val: "180 RESEARCHERS", color: "text-blue-400" },
          { label: "GPU CLUSTER", val: "8x NVIDIA H100", color: "text-emerald-400" },
          { label: "AI ENGINE", val: "GEMINI 2.5 PRO", color: "text-violet-400" },
        ],
        ctaLabel: "Open 2D Club Page",
        ctaUrl: "/clubs",
      },
      {
        index: 5,
        id: "literary",
        type: "CLUB",
        title: "05. LITERARY & DEBATE SOCIETY",
        subtitle: "Parliamentary Debate • 120 Members • National Summit",
        color: "#F59E0B",
        z: -76,
        details: "Chartered university forensic, debate, and journal society. Conducting weekly British Parliamentary debates and publishing Campus Voice quarterly.",
        stats: [
          { label: "MEMBERSHIP", val: "120 ORATORS", color: "text-amber-400" },
          { label: "NATIONAL RANK", val: "#3 IN REGION", color: "text-emerald-400" },
          { label: "NEXT SUMMIT", val: "NOV 22, 2026", color: "text-violet-400" },
        ],
        ctaLabel: "Open 2D Club Page",
        ctaUrl: "/clubs",
      },
      {
        index: 6,
        id: "aerospace",
        type: "CLUB",
        title: "06. AEROSPACE & DRONE CORE",
        subtitle: "UAV & Rocketry • 85 Members • Sub-Orbital Lab",
        color: "#10B981",
        z: -92,
        details: "Student aeronautical engineering society building autonomous quadcopters and sounding rockets. Telemetry link active on 433MHz campus antenna.",
        stats: [
          { label: "MEMBERSHIP", val: "85 AERONAUTS", color: "text-emerald-400" },
          { label: "DRONE FLEET", val: "12 ACTIVE UAVS", color: "text-cyan-400" },
          { label: "LAUNCH SITE", val: "FIELD 3 PERMIT", color: "text-violet-400" },
        ],
        ctaLabel: "Open 2D Club Page",
        ctaUrl: "/clubs",
      },
    ],
  },

  LINE_B: {
    id: "LINE_B",
    name: "LINE B // UPCOMING EVENTS & CHAMPIONSHIPS",
    shortName: "EVENTS METRO",
    badge: "5 STATIONS",
    themeColor: "#F59E0B",
    secondaryColor: "#EC4899",
    bgClass: "bg-amber-500/15 text-amber-300 border-amber-400/50",
    stations: [
      {
        index: 1,
        id: "hackplanet_event",
        type: "EVENT",
        title: "01. HACKPLANET 2026 FLAGSHIP",
        subtitle: "Oct 15–17, 2026 • 1,116 / 1,500 Seats • $10,000 Prize Pool",
        color: "#F59E0B",
        z: -12,
        details: "University Annual Flagship Hackathon. 36 hours of continuous building, mentorship, and VC judging. Holographic QR Pass #ORGOS-2026-8891 active.",
        stats: [
          { label: "SEATS FILLED", val: "1,116 / 1,500", color: "text-amber-400" },
          { label: "PRIZE POOL", val: "$10,000 USD", color: "text-emerald-400" },
          { label: "VENUE", val: "MAIN ARENA HALL", color: "text-pink-400" },
        ],
        ctaLabel: "Open 2D Events Page",
        ctaUrl: "/events",
      },
      {
        index: 2,
        id: "rover_war",
        type: "EVENT",
        title: "02. ROBOTICS ROVER WAR 2026",
        subtitle: "Nov 04, 2026 • 32 Competing Squads • Outdoor Stadium",
        color: "#06B6D4",
        z: -28,
        details: "National Autonomous Rover obstacle course and LiDAR challenge. Watch 32 university squads battle across simulated Martian terrain.",
        stats: [
          { label: "COMPETING SQUADS", val: "32 FINALISTS", color: "text-cyan-400" },
          { label: "FIRST PRIZE", val: "$4,500 + NVIDIA KIT", color: "text-emerald-400" },
          { label: "VENUE", val: "STADIUM TRACK B", color: "text-violet-400" },
        ],
        ctaLabel: "Open 2D Events Page",
        ctaUrl: "/events",
      },
      {
        index: 3,
        id: "symphony_live",
        type: "EVENT",
        title: "03. SYMPHONY NIGHT LIVE CONCERT",
        subtitle: "Nov 18, 2026 • 2,400 RSVP Tickets • Open Air Theatre",
        color: "#EC4899",
        z: -44,
        details: "Annual open-air musical gala featuring 85-piece student symphony orchestra and acoustic electronic fusion bands. Free campus entry with QR pass.",
        stats: [
          { label: "RSVP TICKETS", val: "2,400 ISSUED", color: "text-pink-400" },
          { label: "GUEST ARTISTS", val: "3 HEADLINERS", color: "text-emerald-400" },
          { label: "VENUE", val: "OPEN AIR THEATRE", color: "text-violet-400" },
        ],
        ctaLabel: "Open 2D Events Page",
        ctaUrl: "/events",
      },
      {
        index: 4,
        id: "algo_hackathon",
        type: "EVENT",
        title: "04. QUANT TRADING ALGO SPRINT",
        subtitle: "Dec 02, 2026 • 400 Trading Teams • High-Frequency Server",
        color: "#7C3AED",
        z: -60,
        details: "8-hour quantitative options pricing and automated trading competition hosted by ABACUS Society on simulated exchange servers.",
        stats: [
          { label: "REGISTERED TEAMS", val: "400 TRADERS", color: "text-violet-400" },
          { label: "SERVER LATENCY", val: "0.4ms SIMULATED", color: "text-emerald-400" },
          { label: "VENUE", val: "FINANCE LAB 101", color: "text-cyan-400" },
        ],
        ctaLabel: "Open 2D Events Page",
        ctaUrl: "/events",
      },
      {
        index: 5,
        id: "leadership_summit",
        type: "EVENT",
        title: "05. ANNUAL LEADERSHIP & GOVERNANCE SUMMIT",
        subtitle: "Dec 14, 2026 • All 9 Club Presidents • Main Auditorium",
        color: "#10B981",
        z: -76,
        details: "Annual executive session where all 9 chartered student organization presidents present yearly budget audits and elect next academic council.",
        stats: [
          { label: "ATTENDANCE", val: "ALL 9 COUNCILS", color: "text-emerald-400" },
          { label: "AUDIT ACCURACY", val: "100% PRISMA SYNC", color: "text-cyan-400" },
          { label: "VENUE", val: "MAIN AUDITORIUM", color: "text-amber-400" },
        ],
        ctaLabel: "Open 2D Events Page",
        ctaUrl: "/events",
      },
    ],
  },

  LINE_C: {
    id: "LINE_C",
    name: "LINE C // EXECUTIVE GOVERNANCE & SETTINGS",
    shortName: "GOVERNANCE METRO",
    badge: "4 STATIONS",
    themeColor: "#10B981",
    secondaryColor: "#06B6D4",
    bgClass: "bg-emerald-500/15 text-emerald-300 border-emerald-400/50",
    stations: [
      {
        index: 1,
        id: "settings_core",
        type: "GOVERNANCE",
        title: "01. 21-MODULE ENTERPRISE CONSOLE",
        subtitle: "Schema-Driven Administration • 5 Domains • Live State",
        color: "#10B981",
        z: -12,
        details: "Central executive administration suite controlling Workspace, Branding, Security, AI Quotas, and Tamper-Evident Audit Logs across all clubs.",
        stats: [
          { label: "ADMIN MODULES", val: "21 CONFIG READY", color: "text-emerald-400" },
          { label: "DIRTY-STATE", val: "SYNCED WITH DB", color: "text-cyan-400" },
          { label: "SECURITY TIER", val: "ISO-27001", color: "text-violet-400" },
        ],
        ctaLabel: "Open 21-Module Settings",
        ctaUrl: "/settings",
      },
      {
        index: 2,
        id: "rbac_ferpa",
        type: "GOVERNANCE",
        title: "02. FERPA / GDPR COMPLIANCE VAULT",
        subtitle: "Student Directory Privacy • Consent Audit • Zero Leak",
        color: "#06B6D4",
        z: -28,
        details: "Enforces strict academic privacy regulations, campus IP whitelisting, hardware MFA requirements, and automated student consent logging.",
        stats: [
          { label: "FERPA COMPLIANCE", val: "100% PROTECTED", color: "text-cyan-400" },
          { label: "DIRECTORY MASKING", val: "ACTIVE ON ALL CLUBS", color: "text-emerald-400" },
          { label: "MFA ENFORCEMENT", val: "HARDWARE TOTP REQUIRED", color: "text-violet-400" },
        ],
        ctaLabel: "Open 21-Module Settings",
        ctaUrl: "/settings",
      },
      {
        index: 3,
        id: "ai_quotas",
        type: "GOVERNANCE",
        title: "03. AI ENGINE & TOKEN QUOTA COMMAND",
        subtitle: "Gemini 2.5 Pro Enterprise • 100M Monthly Token Pool",
        color: "#7C3AED",
        z: -44,
        details: "Manages AI budget allocations, real-time word filters, attachment MB quotas, and autonomous RSVP reminder cron jobs across the campus.",
        stats: [
          { label: "AI MODEL", val: "GEMINI 2.5 PRO", color: "text-violet-400" },
          { label: "TOKEN BUDGET", val: "100M / MONTH", color: "text-cyan-400" },
          { label: "AI MEETINGS", val: "REALTIME SUMMARY", color: "text-emerald-400" },
        ],
        ctaLabel: "Open 21-Module Settings",
        ctaUrl: "/settings",
      },
      {
        index: 4,
        id: "disaster_recovery",
        type: "GOVERNANCE",
        title: "04. DISASTER RECOVERY & ROLLBACK VAULT",
        subtitle: "Golden Snapshot Baseline • Safe Mode Break-Glass",
        color: "#F59E0B",
        z: -60,
        details: "Tamper-evident cryptographic audit logs, hourly PostgreSQL database snapshots, and emergency break-glass read-only Safe Mode toggle.",
        stats: [
          { label: "SNAPSHOT BASELINE", val: "v2.4.0 GOLDEN", color: "text-amber-400" },
          { label: "AUDIT LOGS", val: "CRYPTOGRAPHIC HASH", color: "text-emerald-400" },
          { label: "SAFE MODE", val: "STANDBY READY", color: "text-pink-400" },
        ],
        ctaLabel: "Open Admin Center",
        ctaUrl: "/admin",
      },
    ],
  },
};
